id: P003048
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 10:36:58.900236
source_metadata:
  id: bdr:W1KG6295
  title: གྲུབ་མཐའི་བསྟན་བཅོས་མི་ཤིག་རྡོ་རྗེའི་གོ་ཆ།
  author: ''
  volumes:
    c3aa0bd3355748debc38c96d94bdb287:
      image_group_id: I1KG6315
      title: ''
      volume_number: 1
      total_pages: 194
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
